# Home Assistant - Open source home automation that puts local control and privacy first.
version: '3.3'

services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    container_name: homeassistant
    volumes:
      - "${TARGET_DIR}/config/homeassistant:/config"
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8123:8123
    restart: always
    networks:
        - iot