# Eclipse Mosquitto is an open source message broker which implements MQTT version 5, 3.1.1 and 3.1
version: '3.3'

services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    volumes:
      - "${TARGET_DIR}/config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf"
      - "${TARGET_DIR}/config/mosquitto/passwd:/etc/mosquitto/passwd"
      - "${TARGET_DIR}/data/mosquitto:/mosquitto/data"
      - "${TARGET_DIR}/log/mosquitto:/mosquitto/log"
    ports:
      - 1883:1883 # expect MQTT packets
      - 9001:9001 # expect HTTP/Websocket protocol, client could be run from a web browser
    restart: always
    networks:
        - iot