# Transmission is designed for easy, powerful use. 
# Transmission has the features you want from a BitTorrent client: 
# encryption, a web interface, peer exchange, magnet links, DHT, µTP, UPnP and NAT-PMP port forwarding, webseed support, watch directories, tracker editing, global and per-torrent speed limits, and more.
version: '3.3'

services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - "PUID=${USER_ID}"
      - "PGID=${GROUP_ID}"
      - TZ=Europe/London
      - "FILE__PASSWORD=${TARGET_DIR}/secrets/password"
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional Specify an alternative UI options are /combustion-release/, /transmission-web-control/, /kettu/ and /flood-for-transmission/.
      - "USER=${TRANSMISSION_USERNAME}" #optional Specify an optional username for the interface
      - "PASS=${TRANSMISSION_PASSWORD}" #optional Specify an optional password for the interface
      # - WHITELIST=iplist #optional Specify an optional list of comma separated ip whitelist. Fill rpc-whitelist setting.
      # - HOST_WHITELIST=dnsnane list #optional Specify an optional list of comma separated dns name whitelist. Fill rpc-host-whitelist setting
    volumes:
      - "${TARGET_DIR}/config/transmission:/config"
      - "${TARGET_DIR}/downloads/watch:/watch"
      - "${TARGET_DIR}/downloads:/downloads"
    ports:
      - 9091:9091 # WebUI
      - 51413:51413 # Torrent Port TCP
      - 51413:51413/udp # Torrent Port UDP
    restart: always
    networks:
        - media