title: "Home Network"
subtitle: "Homer"
logo: "assets/logo.png"
header: false
footer: false
columns: "auto"
connectivityCheck: true

services:
  - name: "Media"
    icon: "fas fa-code-branch"
    items:
      - name: "PLex"
        logo: "assets/tools/sample2.png"
        tag: "Media"
        tagstyle: "is-success"
        url: "http://127.0.0.1:32400/web"
        target: "_blank"
      - name: "Overseerr"
        logo: "assets/tools/sample2.png"
        tag: "Media"
        tagstyle: "is-success"
        url: "http://127.0.0.1:5055"
        target: "_blank"
      - name: "Sonarr"
        logo: "assets/tools/sample2.png"
        tag: "Media"
        tagstyle: "is-success"
        url: "http://127.0.0.1:8989"
        target: "_blank"
      - name: "Radarr"
        logo: "assets/tools/sample2.png"
        tag: "Media"
        tagstyle: "is-success"
        url: "http://127.0.0.1:7878"
        target: "_blank"
      - name: "Transmission"
        logo: "assets/tools/sample2.png"
        tag: "Media"
        tagstyle: "is-success"
        url: "http://127.0.0.1:9091"
        target: "_blank"
      - name: "Jackett"
        logo: "assets/tools/sample2.png"
        tag: "Media"
        tagstyle: "is-success"
        url: "http://127.0.0.1:9117"
        target: "_blank"
      - name: "Synclounge"
        logo: "assets/tools/sample2.png"
        tag: "Media"
        tagstyle: "is-success"
        url: "http://127.0.0.1:8088"
        target: "_blank"
      - name: "Bazarr"
        logo: "assets/tools/sample2.png"
        tag: "Media"
        tagstyle: "is-success"
        url: "http://127.0.0.1:6767"
        target: "_blank"
  - name: "Music"
    icon: "fas fa-code-branch"
    items:
      - name: "Mstream"
        logo: "assets/tools/sample.png"
        tag: "Music"
        url: "http://127.0.0.1:3000"
        target: "_blank"
      - name: "Deemix"
        logo: "assets/tools/sample.png"
        tag: "Music"
        url: "http://127.0.0.1:6595"
        target: "_blank"
      - name: "Deemix ARL"
        logo: "assets/tools/sample.png"
        tag: "Music"
        url: "https://www.deezer.com/en/"
        target: "_blank"
  - name: "Books"
    icon: "fas fa-code-branch"
    items:
      - name: "Lazylibrarian"
        logo: "assets/tools/sample2.png"
        tag: "Book"
        tagstyle: "is-success"
        url: "http://127.0.0.1:5299/home"
        target: "_blank"
      - name: "Calibre-Web"
        logo: "assets/tools/sample2.png"
        tag: "Book"
        tagstyle: "is-success"
        url: "http://127.0.0.1:8083"
        target: "_blank"
  - name: "Application"
    icon: "fas fa-code-branch"
    items:
      - name: "Portainer"
        logo: "assets/tools/sample.png"
        tag: "App"
        url: "http://127.0.0.1:9000"
        target: "_blank"